@startuml p300-behaviours
!theme plain
title P300 Trial Behaviours

namespace Stimulus {
    namespace Presentation.Standard {
        circle "Colour Toggle Stimulus Presenter" as presenter
    }

    namespace Collections {
        circle "Stimulus Presenter Collection" as collection
    }

    collection o.u. presenter
}

namespace Utilities {
    circle "Black White Matrix Factory" as bw_matrix
    circle "Context Aware Utilities" as context
    circle "Array Utilities" as arrays

    context --> arrays
}

namespace Behaviours.Trialing.P300 {
    abstract P300TrialBehaviour {
        StimulusPresenterCollection PresenterCollection
        int FlashesPerOption
        float OnTime
        float OffTime
    }
    P300TrialBehaviour::PresenterCollection -- .Stimulus.Collections.collection
    P300TrialBehaviour ..> .Stimulus.Presentation.Standard.presenter

    class SingleFlashTrialBehaviour extends P300TrialBehaviour
    SingleFlashTrialBehaviour --> .Utilities.arrays
    class ContextAwareSingleFlashTrialBehaviour extends SingleFlashTrialBehaviour
    ContextAwareSingleFlashTrialBehaviour --> .Utilities.context

    abstract MultiFlashTrialBehaviour extends P300TrialBehaviour
    class ContextAwareMultiFlashTrialBehaviour extends MultiFlashTrialBehaviour
    ContextAwareMultiFlashTrialBehaviour --> .Utilities.context

    abstract GridFlashTrialBehaviour extends MultiFlashTrialBehaviour {
        int Rows
        int Columns
    }
    class RowColumnFlashTrialBehaviour extends GridFlashTrialBehaviour
    RowColumnFlashTrialBehaviour --> .Utilities.arrays
    class CheckerboardFlashTrialBehaviour extends GridFlashTrialBehaviour
    CheckerboardFlashTrialBehaviour --> .Utilities.bw_matrix
}

@enduml