@startuml interaction
!theme plain
title
System Interaction
end title

cloud "Lab Streaming Layer" as lsl {
    card "Markers" as markers
    card "Predictions" as predictions
    card "Data" as data
}

node "Back End (Python)" as back_end
markers --> back_end
predictions <-- back_end

node "Front End (Unity)" as front_end
front_end --> markers
front_end <-- predictions

node "EEG Headset" as headset
data <-- headset
data --> back_end


node "Application" as app

app .> front_end
app <.[norank]. front_end

actor User
app --> User
User -> headset

@enduml