@startuml training-behaviours
!theme plain
title Training Behaviours

namespace Behaviours {
    circle CoroutineBehaviour

    interface Behaviours.IBCIMarkerSource {
        LSLMarkerWriter MarkerWriter
    }

    namespace Trials {
        circle TrialBehaviour
    }
}

namespace Behaviours.Training {
    abstract TrainingBehaviour extends Behaviours.CoroutineBehaviour implements Behaviours.IBCIMarkerSource
    abstract TargetIndicationBehaviour {
        {abstract} int OptionCount
        {abstract} void BeginTargetIndication(int)
        {abstract} void EndTargetIndication()
    }
    interface ITargetable {
        void StartTargetIndication()
        void EndTargetIndication()
    }
    TargetIndicationBehaviour::BeginTargetIndication ..> ITargetable::StartTargetIndication

    circle "Custom Training Behaviours" as custom
    TrainingBehaviour <|-- custom

    class SingleRoundTrainingBehaviour extends TrainingBehaviour {
        int TargetIndex
        float TargetIndicationPeriod
        bool PersistTargetIndication
        float PreTrialTime
        float PostTrialTime
        bool SelectTrainingTarget
        IEnumerator RunRound(int)
    }
    SingleRoundTrainingBehaviour --> TargetIndicationBehaviour
    SingleRoundTrainingBehaviour --> .Behaviours.Trials.TrialBehaviour

    class AutomatedTrainingBehaviour extends SingleRoundTrainingBehaviour {
        int SelectionCount
        float RestTime
    }

    class IterativeTrainingBehaviour extends AutomatedTrainingBehaviour {
        int SelectionsBeforeTraining
        int SelectionsBetweenTraining
    }
}

@enduml