@startuml selection
!theme plain
title Selection

namespace Selection {
    interface IPredictionSink {
        void OnPrediction(Prediction)
    }
    IPredictionSink::OnPrediction --> .LSLFramework.Prediction

    abstract SelectionBehaviour implements IPredictionSink

    interface ISelectable {
        bool IsSelectable
        void Select()
    }

    class SelectorShortcuts {
        IndexedKeyBindSet Bindings
        ..serialized fields..
        - SelectionBehaviour _target
        - TrialBehaviour _trialBehaviour
    }
    SelectionBehaviour -o SelectorShortcuts::_target

    class StimulusPresenterCollectionSelector extends SelectionBehaviour {
        - StimulusPresenterCollection _target
    }
    StimulusPresenterCollectionSelector::_target -> .Stimulus.Collections.StimulusPresenterCollection
    StimulusPresenterCollectionSelector ..> ISelectable::Select
    StimulusPresenterCollection o. ISelectable

    note as Note
        A brief collection of structural skeletons
        enabling operability with training behaviours
        without imposing opinionated selection logic
    end note
}

@enduml