@startuml interaction
!theme plain
title
System Interaction
end title

cloud "Lab Streaming Layer" as lsl {
    card "Markers" as markers
    card "Predictions" as predictions
    card "Data" as data
}

node "BCI Essentials Python" as bessy_py
markers --> bessy_py
predictions <-- bessy_py

node "BCI Essentials Unity" as bessy_u
bessy_u --> markers
bessy_u <-- predictions

node "EEG Headset" as headset
data <-- headset
data --> bessy_py


node "Unity Application" as app

app .> bessy_u
app <.[norank]. bessy_u

actor User
app --> User
User -> headset

@enduml