@startuml overview
!theme plain
title
Essential Class Overview
end title

namespace Behaviours {
    class BCIController extends CommunicationComponentProvider {
        StartTrial()
        InterruptTrial()
        StartTraining()
        InterruptTraining()
    }

    class CommunicationComponentProvider {
        # ProvideCommunicationComponentsToChildren()
        UpdateClassifier()
    }

    namespace Trialing {
        abstract TrialBehaviour {
            # int? TrainingTarget
            void StartTestingTrial()
            void StartTrainingTrial()
            void ClearTrainingTarget()
        }
    }

    namespace Training {
        abstract TrainingBehaviour
    }

    BCIController --> TrialBehaviour
    BCIController --> TrainingBehaviour

    namespace Selection {
        interface ISelector {
            void MakeSelection(int)
        }
    }
    CommunicationComponentProvider ..> ISelector
}

namespace LSLFramework {
    class LSLMarkerWriter {
        PushTrialStartedMarker()
        PushTrainingCompleteMarker()
        ...
        ..
        PushMITrainingMarker(...)
        PushSSVEPClassificationMarker(...)
        ...
    }

    class LSLResponseProvider {
        float PollingPeriod
        --
        SubscribePredictions(callback)
        ...
        Unsubscribe(callback)
        ...
    }
}

CommunicationComponentProvider o-- LSLMarkerWriter
CommunicationComponentProvider o-- LSLResponseProvider

TrialBehaviour --> LSLMarkerWriter
TrainingBehaviour --> LSLMarkerWriter

abstract Stimulus.Presentation.StimulusPresentationBehaviour
TrialBehaviour --> StimulusPresentationBehaviour

@enduml