@startuml stimulus
!theme plain
title
Stimulus Classes
end title

namespace Stimulus {
    class StimulusPresenterCollection {
        List<StimulusPresenter> LatestSubset
        ..serialized fields..
        # List<StimulusPresenter> _stimulusPresenters
        --
        StimulusPresenter this[int]
        List<StimulusPresenter> GetSelectable()
        List<StimulusPresenter> GetVisible()
        List<StimulusPresenter> GetVisibleAndSelectable()
        --
        int Count
        void Clear()
        void Add(StimulusPresenter)
        void Remove(StimulusPresenter)
        bool Contains(StimulusPresenter)
        void CopyTo(StimulusPresenter[], int)
        IEnumerator GetEnumerator()
    }

    class DynamicStimulusPresenterCollection extends StimulusPresenterCollection {
        SearchMethod PopulationMethod { Type | Tag }
        Scope PopulationScope { Scene | Children | ChildrenOfParent }
        string PresenterTag {"BCI"}
        bool RepopulateWhenQueried
        void Repopulate()
        List<StimulusPresenter> GetSelectable()
        List<StimulusPresenter> GetVisible()
    }
    
    StimulusPresenterCollection::_stimulusPresenters o- StimulusPresenter

' ---

    abstract StimulusPresenter {
        bool IsSelectable
        {abstract} void StartStimulusDisplay()
        {abstract} void EndStimulusDisplay()
        {abstract} void Select()
        {abstract} void StartTargetIndication()
        {abstract} void EndTargetIndication()
    }

    abstract CoroutineStimulusPresenter extends StimulusPresenter
    {
        {abstract} IEnumerator RunStimulusDisplay()
        {abstract} IEnumerator RunStimulusCleanup()
        {abstract} IEnumerator RunSelection()
        {abstract} IEnumerator RunTargetIndication()
        {abstract} IEnumerator RunTargetIndicationCleanup()
    }

    class UnityEventStimulusPresenter extends StimulusPresenter {
        UnityEvent OnStimulusDisplayTriggered
        UnityEvent OnStimulusDisplayEnded
        UnityEvent OnSelected
        UnityEvent OnTargeted
        UnityEvent OnTargettingEnded
    }

' ---

    class ColourFlashDisplay {
        bool IsFlashing
        Renderer Renderer
        Color OnColour
        Color OffColour
        ..target indication..
        float TargetIndicationFlashPeriod
        float TargetIndicationFlashCount
        ..selection indication..
        SelectionFlashPeriod
        SelectionFlashCount
        ---
        void StartSelectionIndication()
        void StopSelectionIndication()
        void StartTargetIndication()
        void EndStartedIndication()
        ..
        void DisplayOnColour()
        void DisplayOffColour()
        void ToggleDisplayState(bool)
        void SetColour(Color)
    }

    class DutyCycleEngine {
        float Frequency
        float DutyCycle
        bool StateFlag
        bool IsRunning
        ---
        void StartCycle()
        void StopCycle()
    }


    class ColourToggleStimulusPresenter extends StimulusPresenter
    ColourToggleStimulusPresenter o- ColourFlashDisplay

    class FrequencyStimulusPresenter extends ColourToggleStimulusPresenter
    FrequencyStimulusPresenter o- DutyCycleEngine
}

@enduml