@startuml overview
!theme plain
title Essential Class Overview


abstract class BCICommandCentre


abstract TrialConductor {
    # int? TrainingTarget
    void StartTestingTrial()
    void StartTrainingTrial()
    void ClearTrainingTarget()
}

class AutomatedTrainingConductor

BCICommandCentre o- TrialConductor
BCICommandCentre o-- AutomatedTrainingConductor


namespace LSLFramework {
    class LSLMarkerWriter {
        PushTrialStartedMarker()
        PushTrainingCompleteMarker()
        ...
        ..
        PushMITrainingMarker(...)
        PushSSVEPClassificationMarker(...)
        ...
    }

    class LSLResponseProvider {
        float PollingPeriod
        --
        SubscribePredictions(callback)
        ...
        Unsubscribe(callback)
        ...
    }
}

BCICommandCentre o-- LSLMarkerWriter
BCICommandCentre o-- LSLResponseProvider

TrialConductor --> LSLMarkerWriter
AutomatedTrainingConductor --> LSLMarkerWriter
TrialConductor <.. AutomatedTrainingConductor


namespace Stimulus {
    circle "Stimulus Presenters" as presenters
}

TrialConductor ..> presenters

@enduml