@startuml overview
!theme plain
title Essential Class Overview


interface Selection.ISelector {
    void MakeSelection(int)
}

namespace Stimulus.Presentation {
    circle "Stimulus Presenters" as presenters
}


namespace Behaviours {
    class BCIController extends CommunicationComponentProvider {
        StartTrial()
        InterruptTrial()
        StartTraining()
        InterruptTraining()
    }

    class CommunicationComponentProvider {
        # ProvideCommunicationComponentsToChildren()
        UpdateClassifier()
    }

    namespace Trialing {
        abstract TrialBehaviour {
            # int? TrainingTarget
            void StartTestingTrial()
            void StartTrainingTrial()
            void ClearTrainingTarget()
        }
    }

    namespace Training {
        abstract TrainingBehaviour
    }

    BCIController --> TrialBehaviour
    BCIController --> TrainingBehaviour
    CommunicationComponentProvider .> ISelector
}

namespace LSLFramework {
    class LSLMarkerWriter {
        PushTrialStartedMarker()
        PushTrainingCompleteMarker()
        ...
        ..
        PushMITrainingMarker(...)
        PushSSVEPClassificationMarker(...)
        ...
    }

    class LSLResponseProvider {
        float PollingPeriod
        --
        SubscribePredictions(callback)
        ...
        Unsubscribe(callback)
        ...
    }
}

CommunicationComponentProvider o-- LSLMarkerWriter
CommunicationComponentProvider o-- LSLResponseProvider

TrialBehaviour --> LSLMarkerWriter
TrainingBehaviour --> LSLMarkerWriter
TrialBehaviour <. TrainingBehaviour

TrialBehaviour ..> presenters

@enduml